CREATE TABLE IF NOT EXISTS users (
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
UNIQUE KEY uk_user_friend (user_id, friend_id),
KEY idx_friend (friend_id),
CONSTRAINT fk_contacts_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS conversations (
id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
type TINYINT NOT NULL, -- 1=single,2=group
title VARCHAR(128) DEFAULT NULL,
owner_id BIGINT UNSIGNED DEFAULT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS participants (
id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
conversation_id BIGINT UNSIGNED NOT NULL,
user_id BIGINT UNSIGNED NOT NULL,
role TINYINT NOT NULL DEFAULT 0, -- 0=member,1=admin,2=owner
muted TINYINT NOT NULL DEFAULT 0,
joined_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
last_seen_at TIMESTAMP NULL DEFAULT NULL,
UNIQUE KEY uk_conv_user (conversation_id, user_id),
KEY idx_user (user_id),
CONSTRAINT fk_part_conv FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE,
CONSTRAINT fk_part_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS messages (
id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
conversation_id BIGINT UNSIGNED NOT NULL,
sender_id BIGINT UNSIGNED NOT NULL,
client_msg_id VARCHAR(64) NOT NULL,
seq BIGINT UNSIGNED NOT NULL,
content_type TINYINT NOT NULL,
content JSON NOT NULL, -- 存 Text/MediaRef/CallBody
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
UNIQUE KEY uk_conv_seq (conversation_id, seq),
UNIQUE KEY uk_sender_client (sender_id, client_msg_id),
KEY idx_conv_time (conversation_id, created_at),
CONSTRAINT fk_msg_conv FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS inbox (
user_id BIGINT UNSIGNED NOT NULL,
conversation_id BIGINT UNSIGNED NOT NULL,
last_read_seq BIGINT UNSIGNED NOT NULL DEFAULT 0,
last_delivered_seq BIGINT UNSIGNED NOT NULL DEFAULT 0,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (user_id, conversation_id),
KEY idx_conv_user (conversation_id, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- Outbox 事务消息表（用于 Kafka 外发）
CREATE TABLE IF NOT EXISTS outbox (
id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
conversation_id BIGINT UNSIGNED NOT NULL,
message_id BIGINT UNSIGNED NOT NULL,
payload JSON NOT NULL,
status TINYINT NOT NULL DEFAULT 0, -- 0=pending,1=published,2=failed
retry_count INT NOT NULL DEFAULT 0,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
KEY idx_status (status),
KEY idx_conv (conversation_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS attachments (
id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
object_key VARCHAR(255) NOT NULL UNIQUE,
uploader_id BIGINT UNSIGNED NOT NULL,
size_bytes BIGINT UNSIGNED NOT NULL,
content_type VARCHAR(128) NOT NULL,
md5 CHAR(32) DEFAULT NULL,
metadata JSON NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;