services:                                     # 要跑哪些容器
  mysql:                                      # 服务名
    image: mysql:8.3                          # 镜像
    container_name: auth_mysql                # 容器名
    environment:                              # 环境变量
      MYSQL_DATABASE: auth_service
      MYSQL_ROOT_PASSWORD: wkr1835484520
    ports: ["3306:3306"]                      # 电脑本地端口 : 容器内部端口
  redis:
    image: redis:7.2-alpine
    container_name: auth_redis
    ports: ["6379:6379"]